apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thunder-device-plugin.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "thunder-device-plugin.labels" . | nindent 4 }}
